apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
{{- range .Values.microservices }}
  INSTANCE_{{ .name | upper }}_NAME: {{ .displayName }}
{{- end }}
